version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - "echo '{ \"was\": \"http://192.168.68.112:5000/\"}' > config.json"
      - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:$TAG"'@' hello-k8s.yml
artifacts:
  files:
    - '**/*'
  name: flask-web-$(date +%Y-%m-%d)
