version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - "echo '{ \"was\": \"http://192.168.68.112:5000/\"}' > config.json"
artifacts:
  files:
    - '**/*'
  name: flask-web-$(date +%Y-%m-%d)
